DIFFUSION_COEFFICIENT	500.0
EDDY_CONST	0.04
ENTRAIN_COEFF_KS	0.09
ENTRAIN_COEFF_KW	0.9
ERUPTION_MASS	4.78e9
FALL_TIME_THRESHOLD  3600	
INITIAL_PLUME_VELOCITY	140
INITIAL_WATER_CONTENT 0.03	
INTERVAL_PHI     0.1	
MAGMA_DISCHARGE_RATE  4.0e5	
MAGMA_TEMPERATURE	1200
MAX_GRAINSIZE     -5
MIN_GRAINSIZE     5		
MEDIAN_GRAINSIZE	0.0
MESH_SIZE_IN_KM	0.2
MINIMUM_CONTRIBUTION	0
MINIMUM_DEPOSIT_FOR_MD_CALC 1.0
PLUME_RADIUS_CORRECTION	1.0
PLUME_THICKNESS	800
PUMICE_DENSITY  1000	
S_DELTA_FOR_FALL_CALC	100
S_DELTA_FOR_PLUME_CALC  10	
S_MAX    100000	
STD_GRAINSIZE	2.0
VENT_ELEVATION  1300
VENT_EASTING    677963
VENT_NORTHING   3532163
WRITE_COLUMN_FILES	1
WRITE_CONF	1
WRITE_DEPCENT_TRAJECTORY	0
WRITE_DECIMAL_MASSLOADING 0
WRITE_DECIMAL_FALL_TRAJ  0
WRITE_FALL_INFO_FILES	1.0
WRITE_MASSLOADING	1
WRITE_SDIMCUTOFF	1
Z_DELTA	100